-- ============================================================
-- 006 — Galería de la sección "Por qué confiarme"
-- ============================================================
-- Esa sección mostraba un vídeo de presentación. La doctora reportó que
-- grabarlo se estaba complicando, así que el bloque pasa a ser una galería
-- de fotos que ella misma administra: bioseguridad, esterilización y los
-- equipos con los que trabaja (HydraFacial Elite y demás).
--
-- Se sigue el mismo patrón que `procedimiento_galeria` —una fila por foto,
-- con orden explícito— en vez de guardar un array en una sola celda:
--   · reordenar es un UPDATE, no reescribir toda la lista;
--   · borrar una foto no arriesga las demás;
--   · cada foto puede llevar su propio pie, que es lo que convierte una
--     galería en información y no en decoración.
--
-- `orden` decide qué se ve primero. La miniatura del vídeo actual se siembra
-- con orden 0 para que siga abriendo la sección, que es como está hoy.
CREATE TABLE IF NOT EXISTS galeria_confianza (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url         text NOT NULL,
  titulo      text DEFAULT '',
  descripcion text DEFAULT '',
  orden       integer NOT NULL DEFAULT 0,
  creado_en   timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_galeria_confianza_orden
  ON galeria_confianza (orden ASC, id ASC);

COMMENT ON TABLE  galeria_confianza IS 'Fotos de la sección "Por qué confiarme": bioseguridad, esterilización y equipos.';
COMMENT ON COLUMN galeria_confianza.orden IS 'Menor primero. La foto con orden 0 abre la galería.';

-- Siembra: la miniatura que hoy usa el vídeo queda como primera foto, para
-- que la sección no aparezca vacía al desplegar. Solo si la tabla está vacía.
INSERT INTO galeria_confianza (url, titulo, descripcion, orden)
SELECT
  'https://pub-34cf5433a9574d4e9b6b32d8a4cfd815.r2.dev/ConsultorioImagenes/ImagenesPublicas/preview_video.jpg',
  'Tu piel merece lo mejor',
  'Procedimientos adaptados a tus necesidades, de alta calidad.',
  0
WHERE NOT EXISTS (SELECT 1 FROM galeria_confianza);
